# Generated by Django 2.2.17 on 2021-01-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('roll_no', models.CharField(max_length=100)),
                ('maths', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
            ],
        ),
    ]
